[project]
name = "rag-example"
version = "0.1.0"
description = "RAG Project using Amazon Bedrock"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "boto3",
    "botocore",
    "uvicorn",
]
